baseURL = "https://WOVY.github.io/"
languageCode = "ko-kr"
title = "WOVY's Tech Blog"
theme = "PaperMod"
paginate = 10
enableRobotsTXT = true
googleAnalytics = "G-381JTKX1TD"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  section = ["HTML"]

[taxonomies]
  tag = "tags"
  series = "series"

[params]
  author = "WOVY"
  description = "이것저것 기록하는 블로그"
  defaultTheme = "auto"
  disableThemeToggle = false
  images = ["images/favicon.png"]

  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  ShowToc = true
  TocOpen = false
  comments = true
  DateFormat = "2006-01-02"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 2
    keys = ["title", "summary", "tags", "series"]

  [params.profileMode]
    enabled = true
    title = "WOVY"
    subtitle = "이것저것 기록하는 블로그"
    imageUrl = "https://github.com/WOVY.png"
    imageWidth = 130
    imageHeight = 130
    imageTitle = "WOVY"


  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/WOVY"

  [params.giscus]
    repo = "WOVY/WOVY.github.io"
    repoId = "R_kgDOSGjdIw"
    category = "General"
    categoryId = "DIC_kwDOSGjdI84C7L4T"
    mapping = "pathname"
    strict = "0"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "preferred_color_scheme"
    lang = "ko"

  [params.assets]
    disableHLJS = true
    favicon = "images/favicon.png"
    favicon16x16 = "images/favicon.png"
    favicon32x32 = "images/favicon.png"
    apple_touch_icon = "images/favicon.png"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Series"
    url = "/series/"
    weight = 3
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5
